image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: C:\projects
  
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd C:\projects
  # Get Qt and add it to the path
  - curl -L -o Qt.zip https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.13.1/Qt-5.13.1.zip
  - 7z x Qt.zip
  - ps: $env:path="C:\projects\Qt;C:\projects\Qt\bin;$($env:path)"
  - cd
  # Get QtCharts
  - curl -L -o Qtcharts.zip https://github.com/qt/qtcharts/archive/v5.13.1.zip
  - 7z x Qtcharts.zip
  - ren qtcharts-5.13.1 QtCharts
  
build_script:
  - cd C:\projects\QtCharts
  - qmake
  - where nmake
  - nmake
  - ls
  - cd ..

after_build:
  # Pack all the libraries, dlls and include files into one zip
  - cd C:\projects
  - 7z a Qt-5.13.1-Charts.zip QtCharts/bin QtCharts/lib QtCharts/include QtCharts/mkspecs
  
artifacts:
  - path: Qt-5.13.1-Charts.zip

deploy:
  provider: GitHub
  auth_token:
    secure: boWJ9aVfVBpOkBGzWF5yS5/Os3eDUjFfziOY04+LNA+7v+PnMFBtHeMJe2PjK4gm
  artifact: Qt-5.13.1-Charts.zip
  on:
    appveyor_repo_tag: true