image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: C:\projects
  
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\vcvarsall.bat" amd64'
  - cd C:\projects
  # Get nasm, install it and add it to the path
  - curl -L -o nasminst.exe https://www.nasm.us/pub/nasm/releasebuilds/2.14rc15/win64/nasm-2.14rc15-installer-x64.exe
  - start /wait nasminst.exe /S
  - ps: $env:path="C:\Program Files (x86)\nasm;$($env:path)"
  # Get Qt and openSSL
  - git clone --single-branch -b 5.11 https://github.com/qt/qtbase.git Qt --depth 1
  - git clone --single-branch -b OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git openSSL --depth 1

build_script:
  # Build openssl
  - cd openSSL
  - perl Configure VC-WIN64A
  - nmake
  # Build Qt
  - cd C:\projects\Qt
  - .\configure.bat -release -opensource -confirm-license -opengl dynamic -platform win32-msvc2015 -openssl -IC:\projects\openSSL\openSSL-release\include -LC:\projects\openSSL\openSSL-release\lib -nomake examples -nomake tests -no-direct2d
  # start compiling
  - where nmake
  - nmake

after_build:
  