image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: C:\projects
  
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd C:\projects
  # Get Qt and add it to the path
  - curl -L -o Qt.zip https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase5.11/Qt-5.11.zip
  - 7z x Qt.zip
  - ps: $env:path="C:\projects\Qt;C:\projects\Qt\bin;$($env:path)"
  - cd
  # Checkout Qttools
  - git clone --single-branch -b 5.11 https://github.com/qt/qttools.git Qttools --depth 1
  
build_script:
  # Build the tools
  - cd C:\projects\Qttools
  - qmake
  - where nmake
  - nmake
  - ls

after_build:
  