language: cpp
matrix:
  include:
    - os: osx
      env: 
        - OUTPUT_ZIP_FILE=Qtbase-5.13.1_mac.zip
        - OPEN_SSL_FILE=openSSL_1_1_1_stable_mac.zip
        - QT_INSTALL_DIR=/Users/travis/build/Qt
    - os: windows
      env: 
        - OUTPUT_ZIP_FILE=Qtbase-5.13.1_win.zip
        - OPEN_SSL_FILE=openSSL_1_1_1_stable_win.zip
    - os: linux
      dist: trusty
      env:
        - OUTPUT_ZIP_FILE=Qtbase-5.13.1_ubuntu_trusty.zip
        - OPEN_SSL_FILE=openSSL_1_1_1_stable_ubuntu_trusty.zip
        - QT_INSTALL_DIR=/home/travis/build/Qt
compiler:
  - gcc

install:
  - echo ${TRAVIS_BUILD_DIR}
  # Get the precompiled openssl libraries
  - curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/openSSL1.1.1/${OPEN_SSL_FILE} -o openSSL.zip
  - unzip -q -a openSSL.zip
  # Get Qt sources into a folder in which we build it
  - curl -L https://github.com/qt/qtbase/archive/v5.13.1.zip -o Qtbase.zip
  - unzip -q -a Qtbase.zip
  - mv qtbase-5.13.1 Qt_build
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install winflexbison3
      choco install jom
      choco install VisualCppBuildTools
      choco install strawberryperl
      export PATH=$PATH:";C:\Strawberry\perl\bin"
      # We have to remove this perl executable because it clashes with strawberry perl.
      # Strawberry perl is needed because the perl version that comes with git is too old to compile Qt
      rm 'C:\Program Files\Git\usr\bin\perl.exe'
      unset CC
      unset CC_FOR_BUILD
      unset CXX
      unset CXX_FOR_BUILD
    fi

script:
  # Build QtBase and install
  - cd Qt_build
  # Hack to enable qtsync although we did not technically checkout from git
  - mkdir .git
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./configure -release -opensource -confirm-license -prefix $QT_INSTALL_DIR -openssl -I ${TRAVIS_BUILD_DIR}/openSSL/include/ -L ${TRAVIS_BUILD_DIR}/openSSL/ -nomake examples -qt-xcb
      make -j 2
      make install
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ../buildWindows.bat; fi
  - cd ..

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd $QT_INSTALL_DIR/..
      zip --quiet -r ${TRAVIS_BUILD_DIR}/${OUTPUT_ZIP_FILE} Qt/bin Qt/lib Qt/include Qt/mkspecs Qt/plugins
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cd /c/Users/travis/build
      7z a ${TRAVIS_BUILD_DIR}/${OUTPUT_ZIP_FILE} Qt/bin Qt/lib Qt/include Qt/mkspecs Qt/plugins
    fi
  - ls -l
  - cd ${TRAVIS_BUILD_DIR}
  - ls -l

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kz5qfB8zuzBc7rm3u5aHB5oilKWhduGne731/7sNCgYk+QJ6ALrdgXBSwf9QQcvntUJqtm5R+LxK8ulplrfShlLXE5HR+hZDw4MEkrhYvfF4GPtV/YcxeBKYMKJXYmuBv7K22icCPXhcXnsYr8g8/eAyeUmhFL6dia2z2524NVNcLUKBjKo4U55Ann0dSfWb49xQw39oSjLNWBBICoKQsazRKLTC7uucryQO7eYSmb/jPfZ3G5O7/T4BQp85fkyC1xCH21jEypTeaMVzE/Ha0wb5JvC2wQc2YJwZqumqAbghksV5Ydi59/ZX2D2TqauCyu/dQP9fsP503sWZaxuBLgbaWT8pGmk3SaydX00yE/D0fYI99igQSvxACxP07QR6Uvc8Pi5YTQaLAWKa0JpZ3Np5pXEYCtBaTnQqNDNr6JgiQ9zGqXeCd7/ZghLfOLcYeWi1okqnlDk15RdhAKJIbX/CkVnYYG7xPrTwN3aksTQm9bsY4EbzgD8SVLWROqgs6bmUHlWOjKXT2ve+GWkfL41lOp8A1lCRaFtfjTVMD5f7xUzaaGIe+PD+g4CXoEMsa4Cqd7s6E8RoZZ/HN3427ybrH97nUtqoSorNM+Z3Ig5mDzOVUt64UxeWxTjKvN17iBPjQZV4XjFWtaSpdDsyBYTm/ihuegHhydACji857MU=
  file: ${OUTPUT_ZIP_FILE}
  on:
    repo: ChristianFeldmann/YUViewQt
    tags: true