language: cpp
matrix:
  include:
    - os: osx
      #env: DEPLOY_FILE=lib/libHMDecoder.dylib
compiler:
- gcc

install:
# Get the precompiled openssl libraries
- curl https://github.com/ChristianFeldmann/YUViewQt/releases/download/openSSL1.1.1/openSSL_1_1_1_stable_mac.zip -o openSSL.zip
- unzip openSSL.zip
- ls
# Get Qt into a folder in which we build it
- git clone --single-branch -b 5.11 https://github.com/qt/qtbase.git Qt_build --depth 1

script:
- cd Qt_build
- ./configure -release -opensource -openssl -I ../openSSL/include/ -L ../openSSL/lib/ -nomake examples -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcanvas3d -skip qtconnectivity -skip qtdeclarative -skip qtdoc -skip qtgamepad -skip qtgraphicaleffects -skip qtlocation -skip qtmultimedia -skip qtnetworkauth -skip qtpurchasing -skip qtquickcontrols2 -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech -skip qtsvg -skip qttranslations -skip qtvirtualkeyboard -skip qtwayland -skip qtwebchannel -skip qtwebengine -skip qtwebsockets -skip qtwebview -skip qtwinextras -skip qtxmlpatterns
- ls

before_deploy:
  # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv lib/liblibHMDecoderStatic.so lib/libHMDecoder.so; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv lib/liblibHMDecoderStatic.dylib lib/libHMDecoder.dylib; fi

# deploy:
#   skip_cleanup: true
#   provider: releases
#   api_key:
#     secure: Vvkraps4w/N/DCTTCEdOypYMYb7hvfGpaYSBNxxC2Few8XL0lrUGPxr/hWkQEMug0ia8Gh97tI5Fa3y+Fu16pYpivmrQp9avkaQqV7JA4/3Js1LL/qvltlgbzys6pZ/6IncWxPwLV5evCrup8rHUX5yK9qnbF8jICzzsEBeAL+KCI1uDGLgCHwlaVqKkUses0iOsfBwm+UrNdBDj3ycN7nF0cQDCWwGCkjhZeoGSa+9vCwjQdzoC4TGj0VAQq0jJKtJxNx+FRsI1d/rL8HulM987l3Wabe3LStF4Lva4ZIOORMA5iZk2/SABURRNr3CD8j/jckhnAWv9tS7eOcqK5yKvJe6jPBoLcJBysY83XfinY8Mzi6JAWftdrobg1Z3DSbT4jfG5H8wDpJMqJOZQnQbK4did8xawMywRdWciUWnleAtUFeq7ZMVCdti202nct5zKONVgcC72WtnluyNuNUSp7SeCR8T5wIQ6KuX162YDMiPdwTyvXJ9QudNWPabS2/9Og1HtSCCHw5b/XzNkvTu9dsba4ju2vqexWdAjsR1SI6X+gsH5YbF0DbEpKkA+1TM2WEdai9/IMj0RSNdHSeS09vXi3LDAhZ79XKC08x7CwJ45PiyYC9ASrIp1uHQZs8Qd59YwxehdzlHHlw3qXfttWcif4kNHqvR44x/yL6I=
#   file: $DEPLOY_FILE
#   on:
#     repo: ChristianFeldmann/libHM
#     tags: true