name: C/C++ CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-22.04
            openSSLFile: openSSL_3_5_0_ubuntu22.zip
            unzipCommand: unzip -qa
            artifactName: qtBase_6.7.2_ubuntu20
            configureExtra: -DFEATURE_system_xcb_xinput=OFF
          # - os: ubuntu-22.04
          #   openSSLFile: openSSL_1_1_1w_ubuntu22.zip
          #   unzipCommand: unzip -qa
          #   artifactName: qtBase_6.7.2_ubuntu22
          #   configureExtra: -DFEATURE_system_xcb_xinput=OFF
          # - os: windows-2019
          #   openSSLFile: openSSL_1_1_1w_win2019.zip
          #   unzipCommand: 7z x
          #   artifactName: qtBase_6.7.2_win2019
          # - os: windows-2022
          #   openSSLFile: openSSL_1_1_1w_win2022.zip
          #   unzipCommand: 7z x
          #   artifactName: qtBase_6.7.2_win2022
          # - os: macos-12
          #   openSSLFile: openSSL_1_1_1w_mac12.zip
          #   unzipCommand: unzip -qa
          #   artifactName: qtBase_6.7.2_mac12
          #   configureExtra:
          # - os: macos-13
          #   openSSLFile: openSSL_1_1_1w_mac13.zip
          #   unzipCommand: unzip -qa
          #   artifactName: qtBase_6.7.2_mac13
          #   configureExtra:
          # - os: macos-14
          #   openSSLFile: openSSL_1_1_1w_mac14.zip
          #   unzipCommand: unzip -qa
          #   artifactName: qtBase_6.7.2_mac14
          #   configureExtra:

    steps:
    - uses: aseprite/get-ninja@main
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Download precompiled openSSL (windows)
      run: |
        mkdir openSSL
        cd openSSL
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/openSSL3.5/${{matrix.config.openSSLFile}} -o openSSL.zip
        ${{matrix.config.unzipCommand}} openSSL.zip
        cd ..
    - name: Download QtBase Sources
      run: |
        curl -L https://github.com/qt/qtbase/archive/v6.9.0.zip -o QtBase.zip
        ${{matrix.config.unzipCommand}} QtBase.zip
        mv qtbase-6.9.0 Qt_build
    - name: Install Linux Dependencies
      run: sudo apt install build-essential '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev ninja-build
      if: runner.os == 'Linux'
    - name: Build Windows
      run: |
        cd Qt_build
        mkdir .git
        cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_INSTALL_PREFIX="d:\\a\YUViewQt\\YUViewQt\\Qt" -DQT_BUILD_TESTS=OFF -DQT_BUILD_EXAMPLES=OFF -DINPUT_opengl=dynamic -DINPUT_openssl=runtime -DOPENSSL_ROOT_DIR="d:\\a\\YUViewQt\\YUViewQt\\openSSL" -DFEATURE_sql=OFF
        cmake --build . --parallel 2
        cmake --install .
        cd ..
        7z a -r ${{matrix.config.artifactName}}.zip Qt
        dir
      shell: cmd
      if: runner.os == 'Windows'
    - name: Build Mac/Linux
      run: |
        cd Qt_build
        mkdir .git
        cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/Qt -DQT_BUILD_TESTS=OFF -DQT_BUILD_EXAMPLES=OFF -DINPUT_openssl=runtime -DOPENSSL_ROOT_DIR=${GITHUB_WORKSPACE}/openSSL/ ${{matrix.configureExtra}}
        cmake --build . --parallel 2
        cmake --install .
        cd ..
        zip -r ${{matrix.config.artifactName}}.zip Qt
        ls
      if: runner.os != 'Windows'
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.config.artifactName}}
        path: ${{matrix.config.artifactName}}.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{matrix.config.artifactName}}.zip

  # How to upload files to the release:
  # https://github.com/Blacksmoke16/oq/pull/47/files#diff-082c28d748ad2e3eecc5508d740d9417R9-R29
  # This is something but is looks ugly
  # https://github.com/actions/upload-release-asset/issues/17