name: C/C++ CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025, macos-13, macos-15]

    steps:
    - uses: aseprite/get-ninja@main
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set artifact name
      id: artifacts
      shell: bash
      run: |
        echo "OpenSSL file: openssl=openSSL-3-5-0-${{ matrix.os }}"
        echo "openssl=openSSL-3-5-0-${{ matrix.os }}" >> "$GITHUB_OUTPUT"
        echo "Artifact output: output=qtBase-6-9-0-${{ matrix.os }}"
        echo "output=qtBase-6-9-0-${{ matrix.os }}" >> "$GITHUB_OUTPUT"
    - name: Download precompiled openSSL
      shell: bash
      run: |
        mkdir openSSL
        cd openSSL
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/openSSL3.5.0/${{steps.artifacts.outputs.openssl}}.zip -o openSSL.zip
        unzip -qa openSSL.zip
        cd ..
    - name: Download QtBase Sources
      run: |
        curl -L https://github.com/qt/qtbase/archive/v6.9.0.zip -o QtBase.zip
        unzip -qa QtBase.zip
        mv qtbase-6.9.0 Qt_build
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt install build-essential '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev ninja-build
    - name: Build Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        cd Qt_build
        mkdir .git
        cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_INSTALL_PREFIX="d:\\a\YUViewQt\\YUViewQt\\Qt" -DQT_BUILD_TESTS=OFF -DQT_BUILD_EXAMPLES=OFF -DINPUT_opengl=dynamic -DINPUT_openssl=runtime -DOPENSSL_ROOT_DIR="d:\\a\\YUViewQt\\YUViewQt\\openSSL" -DFEATURE_sql=OFF
        cmake --build . --parallel 2
        cmake --install .
        cd ..
        7z a -r ${{steps.artifacts.outputs.output}}.zip Qt
    - name: Build Mac/Linux
      if: runner.os != 'Windows'
      run: |
        cd Qt_build
        mkdir .git
        cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/Qt -DQT_BUILD_TESTS=OFF -DQT_BUILD_EXAMPLES=OFF -DINPUT_openssl=runtime -DOPENSSL_ROOT_DIR=${GITHUB_WORKSPACE}/openSSL/ ${{matrix.configureExtra}}
        cmake --build . --parallel 2
        cmake --install .
        cd ..
        zip -r ${{steps.artifacts.outputs.output}}.zip Qt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{steps.artifacts.outputs.output}}
        path: ${{steps.artifacts.outputs.output}}.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{steps.artifacts.outputs.output}}.zip

  # How to upload files to the release:
  # https://github.com/Blacksmoke16/oq/pull/47/files#diff-082c28d748ad2e3eecc5508d740d9417R9-R29
  # This is something but is looks ugly
  # https://github.com/actions/upload-release-asset/issues/17